CREATE TABLE IF NOT EXISTS books (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    author VARCHAR(500) NOT NULL,
    description TEXT NULL,
    price BIGINT NOT NULL
);

INSERT INTO books (title, author, description, price) VALUES
    ('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic fantasy adventure following the journey of hobbits to destroy the One Ring and defeat the Dark Lord Sauron.', 25),
    ('Pride and Prejudice', 'Jane Austen', 'A classic romance novel exploring the social dynamics and courtship rituals in early 19th-century England.', 15),
    ('1984', 'George Orwell', 'A dystopian social science fiction novel depicting a totalitarian society where the government controls every aspect of life.', 18),
    ('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'A comedic science fiction series following the misadventures of an unsuspecting Englishman after the destruction of Earth.', 20),
    ('To Kill a Mockingbird', 'Harper Lee', 'A novel set in the American South that tackles issues of racial injustice and childhood innocence through the eyes of a young girl.', 22),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 'A story of wealth and illusion set in the Jazz Age, exploring themes of love, loss, and the American Dream.', 18),
    ('Moby Dick', 'Herman Melville', 'The tale of a whaling voyage and one man''s obsessive quest to hunt down a legendary white whale.', 21),
    ('Jane Eyre', 'Charlotte Brontë', 'A gothic romance novel about a young woman''s journey to independence and self-discovery in Victorian England.', 16),
    ('The Catcher in the Rye', 'J.D. Salinger', 'A story of teenage rebellion and alienation, narrated by a disillusioned adolescent in post-World War II America.', 17),
    ('The Hobbit', 'J.R.R. Tolkien', 'A fantasy adventure story about a hobbit who embarks on a quest with dwarves to reclaim their treasure from a dragon.', 24),
    ('Little Women', 'Louisa May Alcott', 'A novel about the lives of four sisters growing up during the American Civil War and their journey to womanhood.', 14),
    ('Animal Farm', 'George Orwell', 'An allegorical satire of the Russian Revolution, depicting the rise of a totalitarian regime led by animals.', 19),
    ('The Shining', 'Stephen King', 'A horror novel about a family''s isolation in a haunted hotel and the descent into madness.', 23),
    ('The Da Vinci Code', 'Dan Brown', 'A mystery thriller that follows a symbologist and cryptologist as they unravel a conspiracy involving secrets hidden within famous works of art.', 20),
    ('The Alchemist', 'Paulo Coelho', 'A philosophical novel about a shepherd boy who follows his dreams and learns about the interconnectedness of the world.', 19),
    ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A crime thriller about a disgraced journalist and a young female hacker who team up to investigate a missing woman.', 21),
    ('The Hunger Games', 'Suzanne Collins', 'A dystopian novel set in a future where teenagers are forced to compete in a televised fight to the death.', 22),
    ('The Book Thief', 'Markus Zusak', 'A novel set in Nazi Germany, narrated by Death, about a young girl who finds solace in stealing books.', 20),
    ('Gone with the Wind', 'Margaret Mitchell', 'A historical romance set in the American South during the Civil War, depicting the lives of plantation owners and their struggles.', 25),
    ('The Grapes of Wrath', 'John Steinbeck', 'A novel about a family of migrant workers during the Great Depression and their search for a better life.', 23),
    ('One Hundred Years of Solitude', 'Gabriel García Márquez', 'A multi-generational story of the Buendía family in the fictional town of Macondo, exploring themes of love, fate, and the cyclical nature of history.', 24),
    ('The Road', 'Cormac McCarthy', 'A post-apocalyptic novel about a father and son who journey through a desolate landscape in search of survival.', 21),
    ('The Help', 'Kathryn Stockett', 'A novel about the lives of African American maids in Mississippi in the 1960s and the relationships they form with the white families they work for.', 18),
    ('The Kite Runner', 'Khaled Hosseini', 'A novel about the friendship between a wealthy boy and his servant''s son in Afghanistan, and the guilt and redemption that follows.', 20),
    ('Life of Pi', 'Yann Martel', 'A philosophical adventure novel about an Indian boy who survives a shipwreck and spends months adrift at sea with a Bengal tiger.', 22),
    ('The Fault in Our Stars', 'John Green', 'A young adult romance about two teenagers with cancer who meet at a support group and fall in love.', 17),
    ('The Martian', 'Andy Weir', 'A science fiction novel about an astronaut who is stranded on Mars and must use his ingenuity to survive.', 21),
    ('Ready Player One', 'Ernest Cline', 'A science fiction adventure set in a virtual reality world, where a teenager goes on a quest to find an Easter egg left by the game''s creator.', 20),
    ('The Silent Patient', 'Alex Michaelides', 'A psychological thriller about a psychotherapist who becomes obsessed with uncovering the secrets of a famous painter who has been convicted of murdering her husband.', 19),
    ('Where the Crawdads Sing', 'Delia Owens', 'A mystery novel about a young woman who raises herself in the marshes of North Carolina and becomes a suspect in the murder of a local man.', 18)
