-- Insert data into the books table (50 books)
INSERT INTO books (title, description, price, publication_date) VALUES
    ('Harry Potter and the Chamber of Secrets', 'The second book in the Harry Potter series, where a mysterious chamber is opened at Hogwarts.', 25.99, '1998-07-02'),
    ('The Shining', 'A horror novel by Stephen King, set in the isolated Overlook Hotel, where a family descends into madness.', 19.99, '1977-01-28'),
    ('Pride and Prejudice', 'A romance novel by Jane Austen, exploring the societal constraints and love in 19th-century England.', 15.99, '1813-01-28'),
    ('Nineteen Eighty-Four', 'A dystopian novel by George Orwell, depicting a totalitarian society under the control of Big Brother.', 12.99, '1949-06-08'),
    ('Murder on the Orient Express', 'A mystery novel by Agatha Christie, where detective Hercule Poirot investigates a murder on a train.', 10.99, '1934-01-01'),
    ('Harry Potter and the Prisoner of Azkaban', 'The third book in the Harry Potter series, featuring the escape of Sirius Black from Azkaban prison.', 27.99, '1999-07-02'),
    ('It', 'A horror novel by Stephen King, about a group of children who face an evil entity in their town.', 22.99, '1986-09-15'),
    ('Sense and Sensibility', 'A romance novel by Jane Austen, following the Dashwood sisters as they navigate love and societal expectations.', 14.99, '1811-10-30'),
    ('Animal Farm', 'An allegorical novella by George Orwell, satirizing the Russian Revolution and its aftermath.', 9.99, '1945-08-17'),
    ('The ABC Murders', 'A mystery novel by Agatha Christie, where Hercule Poirot investigates a series of murders linked by an alphabetical pattern.', 11.99, '1936-01-06'),
    ('The Sun Also Rises', 'A novel by Ernest Hemingway, portraying a group of American and British expatriates in post-World War I Europe.', 17.99, '1926-10-22'),
    ('The Great Gatsby', 'A novel by F. Scott Fitzgerald, set in the Jazz Age, exploring themes of wealth, love, and the American Dream.', 16.99, '1925-04-10'),
    ('To Kill a Mockingbird', 'A novel by Harper Lee, addressing racial injustice and childhood innocence in the American South.', 18.99, '1960-07-11'),
    ('The Adventures of Huckleberry Finn', 'A novel by Mark Twain, satirizing societal norms and racism through the journey of a young boy and a runaway slave.', 14.99, '1884-12-10'),
    ('As I Lay Dying', 'A novel by William Faulkner, using multiple narrators to tell the story of a familys journey to bury their mother.', 12.99, '1930-10-06'),
    ('Mrs Dalloway', 'A novel by Virginia Woolf, detailing a day in the life of a high-society woman in post-World War I England.', 10.99, '1925-05-14'),
    ('One Hundred Years of Solitude', 'A novel by Gabriel Garcia Marquez, chronicling the multi-generational story of the Buendía family in the fictional town of Macondo.', 19.99, '1967-05-30'),
    ('Beloved', 'A novel by Toni Morrison, exploring the legacy of slavery and its impact on a family of former slaves.', 21.99, '1987-10-08'),
    ('Midnights Children', 'A novel by Salman Rushdie, intertwining the history of India with the lives of children born at the stroke of midnight on Indias independence.', 15.99, '1981-06-10'),
    ('The Handmaids Tale', 'A dystopian novel by Margaret Atwood, set in a totalitarian regime where women are subjugated and used for reproductive purposes.', 13.99, '1985-01-01'),
    ('Norwegian Wood', 'A novel by Haruki Murakami, depicting the life of a college student in Tokyo and his relationships during a time of social upheaval.', 16.99, '1987-09-04'),
    ('Half of a Yellow Sun', 'A novel by Chimamanda Ngozi Adichie, set during the Nigerian Civil War, exploring themes of identity, love, and betrayal.', 18.99, '2006-08-22'),
    ('Verity', 'A thriller romance novel by Colleen Hoover, involving a writer who uncovers dark secrets within a family.', 24.99, '2021-05-07'),
    ('Along Came a Spider', 'A novel by James Patterson, featuring detective Alex Cross as he investigates a series of kidnappings.', 27.99, '1993-01-01'),
    ('Safe Harbour', 'A novel by Danielle Steel, telling a story of resilience, loss, and finding love after tragedy.', 26.99, '2003-09-16'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'The first book in the Lord of the Rings series by J.R.R. Tolkien, chronicling the beginning of the quest to destroy the One Ring.', 29.99, '1954-07-29'),
    ('The Hitchhikers Guide to the Galaxy', 'A science fiction comedy novel by Douglas Adams, following the misadventures of Arthur Dent after Earths destruction.', 11.99, '1979-10-12'),
    ('Jane Eyre', 'A gothic romance novel by Charlotte Brontë, detailing the life of a governess and her relationship with Mr. Rochester.', 14.99, '1847-10-16'),
    ('The Count of Monte Cristo', 'An adventure novel by Alexandre Dumas, telling the story of Edmond Dantès wrongful imprisonment and his quest for revenge.', 19.99, '1844-08-28'),
    ('Little Women', 'A coming-of-age novel by Louisa May Alcott, following the lives of the four March sisters during and after the American Civil War.', 12.99, '1868-09-30'),
    ('The Picture of Dorian Gray', 'A gothic and philosophical novel by Oscar Wilde, exploring themes of beauty, morality, and the corrupting influence of hedonism.', 10.99, '1890-07-01'),
    ('Frankenstein', 'A gothic novel by Mary Shelley, telling the story of Victor Frankenstein and the creature he creates.', 11.99, '1818-01-01'),
    ('Dracula', 'A gothic horror novel by Bram Stoker, introducing the character of Count Dracula and his reign of terror.', 12.99, '1897-05-26'),
    ('The War of the Worlds', 'A science fiction novel by H. G. Wells, depicting an alien invasion of Earth and humanitys struggle for survival.', 10.99, '1898-01-01'),
    ('Pride and Prejudice and Zombies', 'A parody novel by Seth Grahame-Smith, combining the original Jane Austen novel with elements of zombie horror.', 15.99, '2009-04-01'),
    ('Abraham Lincoln: Vampire Hunter', 'A horror-fantasy novel by Seth Grahame-Smith, portraying President Lincoln as a vampire hunter.', 16.99, '2010-03-02'),
    ('World War Z', 'A zombie apocalyptic horror novel by Max Brooks, told through a series of interviews documenting a global zombie pandemic.', 17.99, '2006-09-12'),
    ('The Martian', 'A science fiction novel by Andy Weir, following an astronauts lone struggle to survive on Mars after being presumed dead.', 19.99, '2011-02-20'),
    ('Ready Player One', 'A science fiction novel by Ernest Cline, set in a virtual reality world called the OASIS, where a teenager competes in a treasure hunt.', 20.99, '2011-08-16'),
    ('Gone Girl', 'A psychological thriller novel by Gillian Flynn, exploring the mystery surrounding a womans disappearance and the secrets within a marriage.', 22.99, '2012-05-22'),
    ('The Girl with the Dragon Tattoo', 'A psychological thriller novel by Stieg Larsson, involving a disgraced journalist and a young female hacker investigating a womans disappearance.', 21.99, '2005-08-16'),
    ('The Silent Patient', 'A psychological thriller novel by Alex Michaelides, centering on a psychotherapists attempt to treat a famous painter who shot her husband.', 23.99, '2019-02-05'),
    ('The Da Vinci Code', 'A mystery thriller novel by Dan Brown, following a symbologist and cryptologist as they unravel a conspiracy related to the Holy Grail.', 18.99, '2003-03-18'),
     ('Angels & Demons', 'A mystery thriller novel by Dan Brown, featuring symbologist Robert Langdon as he investigates a murder and a threat to the Vatican.', 19.99, '2000-05-01'),
    ('Inferno', 'A mystery thriller novel by Dan Brown, with Robert Langdon trying to decipher clues related to a deadly virus and the works of Dante.', 20.99, '2013-05-14'),
    ('Origin', 'A mystery thriller novel by Dan Brown, where Robert Langdon explores questions about humanitys origin and future.', 21.99, '2017-10-03'),
    ('Harry Potter and the Cursed Child', 'A play script by J.K. Rowling, Jack Thorne, and John Tiffany, continuing the story of Harry Potter as an adult and his son Albus.', 25.99, '2016-07-31'),
    ('Fantastic Beasts and Where to Find Them', 'A screenplay by J.K. Rowling, set in the wizarding world and following the adventures of Newt Scamander.', 27.99, '2016-11-18'),
    ('The Casual Vacancy', 'A novel by J.K. Rowling, depicting the aftermath of a death in a small English village and the ensuing power struggle.', 20.00, '2012-09-27'),
    ('The Silkworm', 'A crime fiction novel by Robert Galbraith (J.K. Rowling), featuring detective Cormoran Strike as he investigates the disappearance of a writer.', 19.00, '2014-06-19'),
    ('Career of Evil', 'A crime fiction novel by Robert Galbraith (J.K. Rowling), with Cormoran Strike and Robin Ellacott investigating a series of disturbing murders.', 20.00, '2015-10-20');
